name: pesquisadorhinos
description: Aplicativo "Qual é o hino?", nomeado também como Pesquisador de Hinos.

version: 1.2.3+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # dependencias do projeto
  sqflite: ^1.3.0
  validators: ^2.0.0+1
  flutter_html: ^0.11.1
  package_info: ^0.4.0+16
  url_launcher: ^5.4.2
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_messaging: ^7.0.3
  characters: ^1.0.0
  flutter_speed_dial: ^1.2.5
  tutorial_coach_mark: ^0.5.2
  shared_preferences: ^0.5.12+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"


flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/database/

  fonts:
    - family: Oxanium
      fonts:
        - asset: fonts/Oxanium-Regular.ttf
        - asset: fonts/Oxanium-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
          
