name: pesquisadorhinos
description: Aplicativo "Qual é o hino?", nomeado também como Pesquisador de Hinos.

version: 1.0.0+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # dependencias do projeto
  sqflite: ^1.3.0
  validators: ^2.0.0+1
  flutter_html: ^0.11.1
  package_info: ^0.4.0+16
  url_launcher: ^5.4.2
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  characters: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/imgs/icon.png"


flutter:
  uses-material-design: true

  assets:
   - assets/imgs/
   - assets/bd/

  fonts:
    - family: Oxanium
      fonts:
        - asset: fonts/Oxanium-Regular.ttf
        - asset: fonts/Oxanium-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
          
