name: pesquisadorhinos
description: Aplicativo "Qual é o hino?", nomeado também como Pesquisador de Hinos.

version: 2.0.0+18

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # dependencias do projeto
  sqflite: ^2.3.3
  validators: ^3.0.0
  flutter_html: ^3.0.0-alpha.6 # Alpha version, needs careful checking
  package_info_plus: ^8.2.1 # Replaces package_info
  url_launcher: ^6.2.6
  firebase_core: ^3.15.1 # Major update
  firebase_analytics: ^11.5.2 # Major update
  firebase_messaging: ^15.2.9 # Major update
  characters: ^1.3.0
  flutter_speed_dial: ^7.0.0 # Major update
  tutorial_coach_mark: ^1.2.11
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/database/

  fonts:
    - family: Oxanium
      fonts:
        - asset: fonts/Oxanium-Regular.ttf
        - asset: fonts/Oxanium-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
